"""remove is_protected field

Revision ID: 406ed4d38bfc
Revises: ed0c3132090b
Create Date: 2026-09-29 16:02:14.460287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406ed4d38bfc'
down_revision: Union[str, Sequence[str], None] = 'ed0c3132090b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_protected')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_protected', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
